---
services:
  client:
    build: client
    tty: true
    stdin_open: true
    cap_add:
      - SYS_ADMIN
    networks:
      custom:
        ipv4_address: 172.23.0.101
    shm_size: '2gb'
    cache_from: user/dns-client:latest
  resolver:
    build: resolver
    tty: true
    stdin_open: true
    networks:
      custom:
        ipv4_address: 172.23.0.53

networks:
  custom:
    ipam:
      config:
        - subnet: 172.23.0.0/24
