---
services:
  client:
    image: ubuntu:21.10
    environment:
      - DISPLAY=:1
    volumes:
      - /tmp/.deb-client:/tmp/.deb-client
      - ./client/scripts:/root/scripts
      - ./client/selenium:/home/ubuntu/selenium
    tty: true
    stdin_open: true
    cap_add:
      - SYS_ADMIN
    networks:
      custom:
        ipv4_address: 172.23.0.101
    shm_size: '2gb'
  resolver:
    build: resolver
    tty: true
    stdin_open: true
    networks:
      custom:
        ipv4_address: 172.23.0.53
networks:
  custom:
    ipam:
      config:
        - subnet: 172.23.0.0/24
