---
services:
  client:
    build: client
    tty: true
    stdin_open: true
    cap_add:
      - SYS_ADMIN
    networks:
      custom:
        ipv4_address: 172.23.0.101
    healthcheck:
      test: ["CMD", "ls", "-l", "/.ready"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  resolver:
    build: resolver
    tty: true
    stdin_open: true
    networks:
      custom:
        ipv4_address: 172.23.0.53

networks:
  custom:
    ipam:
      config:
        - subnet: 172.23.0.0/24
