---
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint_markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint changelog file
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          rules: '/lint/rules/changelog.js'
          config: '/lint/config/changelog.yml'
          args: './CHANGELOG.md'

      - name: Lint other markdown files
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          config: './.github/workflows/config/markdown_lint_config.yml'
          args: './*.md'
          ignore: './CHANGELOG.md'

  lint_yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Yamllint Github Action
        uses: karancode/yamllint-github-action@v2.0.0
        with:
          yamllint_strict: true
          yamllint_comment: true

  verify_arp_on_the_same_network:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Get latest docker-compose
        run: wget "https://github.com/docker/compose/releases/download/v2.0.1/docker-compose-linux-aarch64"  # yamllint disable-line rule:truthy
      - name: Install latest docker-compose
        run: |
          uname -a
          chmod a+x ./docker-compose-linux-aarch64
          mv ./docker-compose-linux-aarch64 /usr/local/bin/docker-compose
      - name: Version information
        run: |
          which docker
          docker --version
          which docker-compose
          docker-compose --version
